jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: azure-build.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: azure-build.yml

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure-build.yml
